# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6001f73f350d13c53772716c152d82a1d1295c3446d3a3795359d108a84cd5982f3ac5ac527299b75539d21db61930d7a31f0e02fbdcb8027caa02066c62010

test:
  secret_key_base: 56f15c58e77ccb327b220fab259817d466ee5f83c741925e852d48dd49bb667b6242372841320553ed9ccb0437bbf87fa3d868f1d9bd42144a6a30977d871428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
